version: "3.9"  # optional since v1.27.0
services:
  testers:
    image: aeissa/um-js
    ports:
      - "3000:3000"
    entrypoint: npm start
  server:
    build: . 
    volumes:
      - .:/app
    ports: 
      - "4000:4000"
    environment:
      APP_ENDPOINT: http://testers:3000
    entrypoint: ./init.sh
  redis:
    image: redis:7
    ports:
      - "6379:6379"
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres