# @format

version: '3.9' # optional since v1.27.0
services:
  cache:
    image: redis:7
    ports:
      - 6379:6379

  db:
    image: postgres:14.7
    ports:
      - 5432:5432
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
    env_file:
      - .env.dev
    environment:
      - POSTGRES_PASSWORD=postgres

  api:
    depends_on:
      - db
    image: 079829475258.dkr.ecr.us-east-1.amazonaws.com/spaced-repetition-api
    ports:
      - 5000:5000
    env_file:
      - .env.dev
    environment:
      PORT: 5000

  auth:
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./users_umbrella:/app
    ports:
      - 4000:4000
    env_file:
      - .env.dev
    environment:
      PORT: 4000
    entrypoint: ./init.sh
