version: "3.9"  # optional since v1.27.0
services:
  server:
    build: . 
    volumes:
      - .:/app
    working_dir: /app
    ports: 
      - "4000:4000"
    entrypoint: ./init.sh
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres